name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
        cache-dependency-path: ./go.sum

    - name: Test
      run: go test -v ./...

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o ./release-win-64/misterfpga-neon68k-unzipper.exe

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -o ./release-linux-64/misterfpga-neon68k-unzipper.exe

    - name: Build Mac
      run: GOOS=darwin GOARCH=amd64 go build -o ./release-mac-64/misterfpga-neon68k-unzipper.exe

    - name: Upload Linux
      uses: actions/upload-artifact@v4
      with:
        name: upload-linux
        path: |
          ./README.md
          ./release-linux-64/misterfpga-neon68k-unzipper.exe

    - name: Upload Windows
      uses: actions/upload-artifact@v4
      with:
        name: upload-windows
        path: |
          ./README.md
          ./release-win-64/misterfpga-neon68k-unzipper.exe

    - name: Upload Mac
      uses: actions/upload-artifact@v4
      with:
        name: upload-mac
        path: |
          ./README.md
          ./release-mac-64/misterfpga-neon68k-unzipper.exe
